### ISSUE TITLE
Error : b'<h1>Unauthorized</h1>\n<h2>Error 401</h2>\n'

### ISSUE THREAD

**Issue by nakarin** [Ruu3f/simplebardapi#2]
I got an error like this.
`
IndexError                                Traceback (most recent call last)
Cell In[13], line 1
----> 1 resp = bard.generate_answer("Hi How are you?")

Cell In[10], line 48, in Bard.generate_answer(self, prompt)
     33 resp = self.session.post(
     34     "https://bard.google.com/_/BardChatUi/data/assistant.lamda.BardFrontendService/StreamGenerate",
     35     params={
   (...)
     45     proxies=self.proxies,
     46 )
     47 print(f"resp.content : {resp.content}")
---> 48 parsed_answer = loads(loads(resp.content.splitlines()[3])[0][2])
     49 return {
     50     "content": parsed_answer[4][0][1][0],
     51     "conversation_id": parsed_answer[1][0],
   (...)
     58     ),
     59 }

IndexError: list index out of range
`
when i try to debug "resp.content" , its shown
`
b'<h1>Unauthorized</h1>\n<h2>Error 401</h2>\n'
`

**Comment by Ruu3f** [comment]
This project is inactive, at least until someone fixes it since I have other things now. Use `pip install bardapi==0.1.38` instead.
